name: IntegrationTest
on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:

jobs:
  test:
    name: ${{ matrix.package.repo }}/${{ matrix.package.group }}
    strategy:
      fail-fast: false
      matrix:
        package:
          - {user: SciML, repo: MethodOfLines.jl, group: Components}
          - {user: SciML, repo: MethodOfLines.jl, group: Sol_Interface}
          - {user: SciML, repo: MethodOfLines.jl, group: MOL_Interface1}
          - {user: SciML, repo: MethodOfLines.jl, group: MOL_Interface2}
          - {user: SciML, repo: MethodOfLines.jl, group: Diffusion}
          - {user: SciML, repo: MethodOfLines.jl, group: Nonlinear_Diffusion}
          - {user: SciML, repo: MethodOfLines.jl, group: 2D_Diffusion}
          - {user: SciML, repo: MethodOfLines.jl, group: Convection}
          - {user: SciML, repo: MethodOfLines.jl, group: Higher_Order}
          - {user: SciML, repo: MethodOfLines.jl, group: Stationary}
          - {user: SciML, repo: MethodOfLines.jl, group: Integrals}
          - {user: SciML, repo: MethodOfLines.jl, group: Burgers}
          - {user: SciML, repo: MethodOfLines.jl, group: DAE}
          - {user: SciML, repo: PDESystemLibrary.jl, group: Core}
          - {user: SciML, repo: NeuralPDE.jl, group: NNPDE1}
          - {user: SciML, repo: NeuralPDE.jl, group: NNPDE2}
    uses: "SciML/.github/.github/workflows/downstream.yml@v1"
    with:
      julia-version: "1"
      owner: "${{ matrix.package.user }}"
      repo: "${{ matrix.package.repo }}"
      group: "${{ matrix.package.group }}"
    secrets: "inherit"
